GET http://localhost:8898/api/posts

###

POST http://localhost:8898/api/posts
Content-Type: application/json

{
  "id": 1,
  "content": "Last Post"
}

###

DELETE http://localhost:8898/api/posts/1

###

GET http://localhost:8898/api/posts/1
